#!/bin/sh

CHOICE=$(printf '%s\n' "⏼  Shutdown" "  Reboot" "  Suspend" "  Lock" "  Logout" "  Hibernate"  | fuzzel -d -p "  Session Menu: ")

case "$CHOICE" in
	"⏼  Shutdown") systemctl poweroff ;;
	"  Reboot") systemctl reboot ;;
	"  Suspend") systemctl suspend ;;
	"  Lock") hyprlock ;;
	"  Logout") hyprctl dispatch exit;;
	"  Hibernate") systemctl hibernate ;;
esac
